server.port=8885
server.servlet.context-path=/

spring.datasource.type=com.alibaba.druid.pool.DruidDataSource
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.url=jdbc:h2:mem:petadoption;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
ucloud.ufile.public-key=placeholder
ucloud.ufile.private-key=placeholder
ucloud.ufile.bucket-name=placeholder
ucloud.ufile.region=placeholder
ucloud.ufile.suffix=placeholder
ucloud.ufile.expires=315360000

mybatis.mapper-locations=classpath:/com/pet/mapper/*.xml
mybatis.type-aliases-package=com.pet.demo.entity

pagehelper.helperDialect=h2
pagehelper.reasonable=true
pagehelper.supportMethodsArguments=true
pagehelper.params=count=countSql

spring.aop.auto=true
spring.resources.static-locations=classpath:/templates,classpath:/static/

